### PR TITLE
added checkout button

### LINKED ISSUE #10: Need of checkout button
Need of checkout button at the bottom of this page below total (95 in this case.)

Screenshot from 2022-08-18 09-12-37

### PR DESCRIPTION
**Pull request by Cypher1002**
**Description**

This PR fixes #10 

**Notes for Reviewers**

### CODE REVIEW

**Comment by kamalbuilds** [comment]
:eyes:  @Cypher1002 compilation error.
image

@Cypher1002 I have resolved the conflict .

**Comment by legendarykamal** [comment]
:eyes:  @Cypher1002 compilation error.
image

@Cypher1002 I have resolved the conflict .

**Review by kamalbuilds — CHANGES_REQUESTED** [review]
Button not defined

**Comment by Cypher1002** [comment]
ok will look into that

**Pull request closed without merging**
