### PR TITLE
changing the size of the book

### PR DESCRIPTION
**Pull request by aigerimmmm**
Hi, all the books has the same size
books

### CODE REVIEW

**Comment by kamalbuilds** [comment]
good @aigerimmmm just one thing more, can you fix the rust book image , its got shrinked?

**Comment by kamalbuilds** [comment]
here replace that img with this 
image

https://www.amazon.in/Rust-Programming-Language-Manga-Guide/dp/1593278284

**Comment by aigerimmmm** [comment]
hey @legendarykamal requested change is made, thanks for the picture, it looks like this now
new_rust

**Review by kamalbuilds — APPROVED** [review]
LGTM

**Comment by kamalbuilds** [comment]
Congratulations🎉 @aigerimmmm  thank you for contributing 😃

**Pull request merged**
